#!/bin/bash -x

# macosfortress_boot_check -- check to make sure that all desired services are running

# commands
SUDO="/usr/bin/sudo"
LAUNCHCTL="/bin/launchctl"
BREW="/usr/local/bin/brew"
PFCTL="/sbin/pfctl"
HEAD="/usr/bin/head"
TAIL="/usr/bin/tail"
# LSOF="/usr/sbin/lsof"
KILLALL="/usr/bin/killall"

# pfctl
if ! [[ "$(${SUDO} ${PFCTL} -s info | ${HEAD} -1 | ${TAIL} -1)" =~ "Status: Enabled" ]]; then
	"${SUDO}" "${LAUNCHCTL}" unload -w /Library/LaunchDaemons/net.openbsd.pf.plist
	"${SUDO}" "${LAUNCHCTL}" load -w /Library/LaunchDaemons/net.openbsd.pf.plist
fi

# squid
# make sure there aren't multiple squid jobs running
if /usr/bin/pgrep squid &>/dev/null; then
	"${SUDO}" "${BREW}" services stop squid
	"${SUDO}" "${KILLALL}" 'squid'
	"${SUDO}" "${KILLALL}" '(squid-1)'
fi
"${SUDO}" "${BREW}" services start squid

# privoxy
if /usr/bin/pgrep privoxy &>/dev/null; then
	"${SUDO}" "${BREW}" services restart privoxy
fi
